server:
  port: 7071
spring:
  application:
    name: citigroup
  datasource:
    url: jdbc:mysql://localhost:3306/citi_group_cup?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
